### ISSUE TITLE
Utilize light-bulb infrastructure for applying auto-fixes

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-visualstudio-extension#175]
2020/10/25: A rough-cut implementation is in place. We can disable it at any time by commenting out the `[Export]` attribute on `FixSuggestedActionsSourceProvider`. There are several items remaining.

- [x] @GabeDeBacker implemented squiggles.
- [x] Initial implementation of lightbulb fixes (using standard VS "fix provider" infrastructure).
- [x] Implement preview.
- [x] Use the persistent span, rather than the contents of the log file, to locate the range to be replaced.
- [x] Don't write bytes directly to disk; update the text buffer instead.
- [x] Don't assume file on disk is UTF-8 (might become moot once we work on the text buffer.
- [ ] Ensure that multi-file replacements are handled correctly.
- [x] Implement SARIF-generating test VSIX to facilitate end-to-end testing.

**Comment by jeffersonking** [comment]
@michaelfanning: Can you attach a SARIF log that includes fixes and the artifact associated with the fix?

**Comment by michaelcfanning** [comment]
See Test.UnitTests.Sarif\TestData\SarifCurrentToVersionOneVisitor\ExpectedOutputs\TwoResultsWithFixes.sarif

@lgolding may have a better example in the sarif-tutorials repo. Also, internally at MS we do have a web scanner that produces this data natively, see me offline for that.

**Comment by lgolding** [comment]
There isn't a fixers sample in the tutorials. But years ago I gave a demo that included fixers. Let me see if I can dig it up. (It's probably old SARIF by now, but we can always run it through `sarif transform`.

**Comment by lgolding** [comment]
Update: No, the demo didn't include fixers.

**Comment by lgolding** [comment]
@michaelcfanning @GabeDeBacker I'm going to close this issue. The only remaining bullet item in the description ("Ensure that multi-file replacements are handled correctly") is hard enough that even the VS linter doesn't do it. If/when we decide we want this, I suggest we open an additional issue.

All other known "tail" work is tracked in other open issues:
- #241: Allow fixes to be applied to expanded embedded content.
- #247: Light bulbs don't appear if source file is opened before the SARIF log file is opened.
- #258: Make Undo work with squiggles and light bulbs.
- #264: FixSuggestedActionsSource throws NRE if there are no errors (this is fixed in my [current PR](https://github.com/microsoft/sarif-visualstudio-extension/pull/265)).
